import Header from '@/components/layout/header/Header'
import './globals.sass'
import type { Metadata } from 'next'
import Footer from '@/components/layout/footer/Footer'

export const metadata: Metadata = {
  title: 'Avto-market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
